version: "3.8"

services:
  app:
    build:
      context: ./student_management_backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
    env_file:
      - ./student_management_backend/.env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: student_management
      POSTGRES_USER: LeDangThuong
      POSTGRES_PASSWORD: H9fwdtuoFG1c
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
